services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: ${POSTGRES_PASSWORD_FILE}
    networks:
      - my-network
    volumes:
      - postgres_data_vol:/var/lib/postgresql
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  client1:
    image: debian_psql
    build: ./debian_psql
    container_name: client1
    environment:
      PGPASSWORD: ${PGPASSWORD}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGHOST: database
    networks:
      - my-network
    depends_on:
      database:
        condition: service_healthy
    command: tail -f /dev/null

  client2:
    image: debian_psql
    build: ./debian_psql
    container_name: client2
    environment:
      PGPASSWORD: ${PGPASSWORD}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGHOST: database
    command: tail -f /dev/null

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data_vol:

secrets:
  db_password:
    file: db_password.txt